### ISSUE TITLE
APIKEY

### ISSUE THREAD

**Issue by vglucas** [Xorfor/HA-PWS#3]
hello, I have some questions to better understand 
1) does it work with any model? 
2) to generate and have your own APIKEY is it necessary to configure HA? (I need to have my own APIKEY, but I don't need HA) 
3) Can the APIKEY be managed outside HA and for any project?

**Comment by Xorfor** [comment]
@vglucas 
1. I will not say that it will work with any model, but in general, if the station is supplied with EasyWeather software (version 1.4.x, 1.5.x, 1.6.x), it is likely that the station will work with this HA Configuration!
2. The API key is required in the EasyWeather software, because this software is build to send the data to Ecowitt or Wunderground. Ecowitt and Wunderground require that you create an account to get their API key. As with this configuration for HA we do NOT send to Ecowitt or Wunderground, but to HA, so the API key only requires a dummy value.
3. As said in 2, the API key is not important for this configurantion

I hope this makes it more clear.

**Comment by vglucas** [comment]
@Xorfor 

1) sorry again, so to get the API key do I always and necessarily have to register for weather underground? 
2) will weather underground provide me with the API key and then can I manage the data?

**Comment by vglucas** [comment]
@Xorfor 

I have seen this product, can it fit?

Bresser 7002580 Stazione Meteo A Colori Wi-Fi Con Sensore Professionale 5 In 1, Bianco https://amzn.eu/d/3f1guI1

**Comment by Xorfor** [comment]
I do not know what you want. Do you want a weather station which can send data to Ecowitt or Wunderground, then check the specifications.  Follow the instructions for your weather station.
I didn't want to store my data on internet. That is why I wrote this configuration for HA, so that I can store the PWS locally in HA.

**Comment by vglucas** [comment]
@Xorfor 

sorry if i'm not very clear, i need a weather station that provides me with my personal APIKEY to be able to use it in my personal IOT projects

**Comment by Xorfor** [comment]
Hmmm. Still not sure why you need an APIKEY. As I said, I am not using Ecowitt or Wunderground. But normally if you create an account with a service provider as Ecowitt or Wunderground, then you get an APIKEY, which is send together with your data to Ecowitt or Wunderground. With that APIKEY, Ecowitt or Wunderground knows that the data is from you, and you can access your data in Ecowitt or Wunderground. If you store your PWS data locally, then you don't need an APIKEY, or you use a dummy APIKEY if the software of the weather station requires one.
